SELECT *
FROM RECIPE;

CREATE SEQUENCE SEQ_BOARD_NO NOCACHE;

BEGIN
   FOR I IN 1..50 LOOP
      INSERT INTO "BOARD" 
      VALUES(SEQ_BOARD_NO.NEXTVAL, 
            SEQ_BOARD_NO.CURRVAL || '번째 게시판',
   '뭘봐요', DEFAULT, DEFAULT, DEFAULT, 1, 4);
   END LOOP;
END;

CREATE SEQUENCE SEQ_BOARD_CODE_NO NOCACHE;

INSERT INTO "BOARD_TYPE"
VALUES (SEQ_BOARD_CODE_NO.NEXTVAL, '쿠킹클래스 게시판'); 

COMMIT;

UPDATE BOARD SET
BOARD_CODE = 3
WHERE BOARD_CODE = 1;

SELECT *
FROM BOARD;

COMMIT;


CREATE SEQUENCE SEQ_BOARD_IMAGE_NO NOCACHE;

COMMIT;

CREATE OR REPLACE FUNCTION NEXT_BOARD_IMAGE_NO
RETURN NUMBER 
IS NUM NUMBER;
BEGIN 
   SELECT SEQ_BOARD_IMAGE_NO.NEXTVAL 
   INTO NUM
   FROM DUAL;
   
   RETURN NUM;
END;

COMMIT;

ALTER TABLE BOARD_COMMENT ADD(PARENT_NO NUMBER NOT NULL);
SELECT * FROM BOARD_COMMENT;


SELECT LEVEL, C.* FROM
	(SELECT BOARD_COMMENT_NO, BOARD_COMMENT_CONTENT,
	TO_CHAR(BOARD_COMMENT_ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') BOARD_COMMENT_ENROLL_DATE,
	BOARD_NO, MEMBER_NO, MEMBER_NICKNAME, MEMBER_PROFILE, BOARD_PARENT_NO, BOARD_COMMENT_DEL_FL
FROM "COMMENT"
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_NO = 1) C
WHERE COMMENT_DEL_FL = 'N'
OR 0 != (SELECT COUNT(*) FROM "COMMENT" SUB
	WHERE SUB.PARENT_NO = C.COMMENT_NO
	AND BOARD_COMMENT_DEL_FL = 'N')
START WITH PARENT_NO IS NULL
CONNECT BY PRIOR COMMENT_NO = PARENT_NO
ORDER SIBLINGS BY COMMENT_NO;


SELECT INQUIRY_NO, INQUIRY_TITLE, INQUIRY_CONTENT,
	INQUIRY_REPLY, MEMBER_NO, MEMBER_NICKNAME
FROM "INQUIRY" JOIN "MEMBER" USING(MEMBER_NO)
WHERE "MEMBER_NO" = 1
ORDER BY INQUIRY_NO DESC;

CREATE SEQUENCE SEQ_INQUIRY_NO NOCACHE;

INSERT INTO INQUIRY 
VALUES (SEQ_INQUIRY_NO.NEXTVAL, 
		'테스트중입니다5', 
		'응????', 
		'테스트테스트', 
		12 );

COMMIT;

INSERT INTO "INQUIRY"
VALUES( SEQ_INQUIRY_NO.NEXTVAL,
		#{inquiryTitle},
		#{inquiryContent},
		NULL,
		#{memberNo}
		);
UPDATE BOARD SET
BOARD_CODE = 3
WHERE BOARD_CODE = 1;
				
UPDATE INQUIRY SET
INQUIRY_REPLY = 'ASDASD'
WHERE INQUIRY_NO = 23;

COMMIT;



SELECT
	BOARD_NO ,
	BOARD_TITLE ,
	BOARD_HITS ,
	MEMBER_NICKNAME,
	CASE
		WHEN SYSDATE - BOARD_ENROLL_DATE < 1 / 24 / 60 THEN FLOOR( (SYSDATE - BOARD_ENROLL_DATE) * 24 * 60 * 60 ) || '초 전'
		WHEN SYSDATE - BOARD_ENROLL_DATE < 1 / 24 THEN FLOOR( (SYSDATE - BOARD_ENROLL_DATE) * 24 * 60) || '분 전'
		WHEN SYSDATE - BOARD_ENROLL_DATE < 1 THEN FLOOR( (SYSDATE - BOARD_ENROLL_DATE) * 24) || '시간 전'
		ELSE TO_CHAR(BOARD_ENROLL_DATE, 'YYYY-MM-DD')
	END BOARD_WRITE_DATE ,
	(
	SELECT
		COUNT(*)
	FROM
		"BOARD_COMMENT" C
	WHERE
		C.BOARD_NO = B.BOARD_NO) COMMENT_COUNT,
	(
	SELECT
		COUNT(*)
	FROM
		"BOARD_LIKE" L
	WHERE
		L.BOARD_NO = B.BOARD_NO) LIKE_COUNT,
	(
	SELECT
		IMG_PATH || IMG_RENAME
	FROM
		BOARD_IMG I
	WHERE
		I.BOARD_NO = B.BOARD_NO
		AND IMG_ORDER = 0) THUMBNAIL
FROM
	"BOARD" B
JOIN "MEMBER"
		USING(MEMBER_NO)
WHERE
	BOARD_DEL_FL = 'N'
	AND BOARD_CODE = 3
	AND BOARD_TITLE LIKE '%테스트%'
ORDER BY
	BOARD_NO DESC
;


SELECT
	BOARD_NO ,
	BOARD_TITLE ,
	READ_COUNT ,
	MEMBER_NICKNAME,
	SELECT
	BOARD_NO,
	BOARD_TITLE,
	BOARD_CONTENT,
	TO_CHAR(BOARD_ENROLL_DATE, 'YYYY-MM-DD') BOARD_ENROLL_DATE,
	BOARD_HITS,
	BOARD_CODE,
	MEMBER_NICKNAME,
	BOARD_TYPE
FROM
	"BOARD"
JOIN MEMBER
		USING(MEMBER_NO)
JOIN BOARD_TYPE
		USING(BOARD_CODE)
WHERE
	BOARD_CODE = 3
	AND BOARD_DEL_FL = 'N'
	AND BOARD_TITLE LIKE '%테스트%'
ORDER BY
	BOARD_NO DESC
	;


SELECT
	BOARD_NO ,
	BOARD_TITLE ,
	READ_COUNT ,
	MEMBER_NICKNAME,
	SELECT
	BOARD_NO,
	BOARD_TITLE,
	BOARD_CONTENT,
	TO_CHAR(BOARD_ENROLL_DATE, 'YYYY-MM-DD') BOARD_ENROLL_DATE,
	BOARD_HITS,
	BOARD_CODE,
	MEMBER_NICKNAME,
	BOARD_TYPE
FROM
	"BOARD"
JOIN MEMBER
		USING(MEMBER_NO)
JOIN BOARD_TYPE
		USING(BOARD_CODE)
WHERE
	BOARD_CODE = 3
	AND BOARD_DEL_FL = 'N'
	AND BOARD_TITLE LIKE '%ㅁㅁㅁㅁ%'
ORDER BY
	BOARD_NO DESC;

UPDATE "MEMBER" SET
MEMBER_DEL_FL = 'N'
WHERE MEMBER_NO = 4;
	

